name: Build the application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:

  build:
    name: flutter build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter hversion: '2.8.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
